// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggY67vAQURCZ0_kXw5OSSpXih3XYwYoU',
    appId: '1:994934113333:web:7fef1abb040471bfed9d7c',
    messagingSenderId: '994934113333',
    projectId: 'attendance-39145',
    authDomain: 'attendance-39145.firebaseapp.com',
    storageBucket: 'attendance-39145.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERF7rgE2GKfn61_wZITDBXSPLsg4noSU',
    appId: '1:994934113333:android:cfc68f02aad85206ed9d7c',
    messagingSenderId: '994934113333',
    projectId: 'attendance-39145',
    storageBucket: 'attendance-39145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI93HBQ4r142oP3aSEAP-FIblpvbbfYFw',
    appId: '1:994934113333:ios:ce04e4c445ef9793ed9d7c',
    messagingSenderId: '994934113333',
    projectId: 'attendance-39145',
    storageBucket: 'attendance-39145.appspot.com',
    iosClientId: '994934113333-3jdgfnnovourrkgfh0p2paqdilmvb2ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
